/**
 * entropy.ts
 * Estimate the Shannon entropy and strength of a random string configuration.
 */

import type { RandomStringOptions, EntropyResult } from './types.js';
import { buildCharset } from './charsets.js';

/**
 * Estimates the entropy of strings generated by the given options.
 *
 * For pattern-based strings, each placeholder contributes independently.
 * For length-based strings, entropy = log2(charsetSize) * effectiveLength.
 *
 * @example
 * const e = estimateEntropy({ length: 32, uppercase: true, lowercase: true, numeric: true });
 * console.log(e.bits);     // ~190
 * console.log(e.strength); // 'very-strong'
 */
export function estimateEntropy(options: RandomStringOptions = {}): EntropyResult {
  const {
    length = 16,
    prefix = '',
    suffix = '',
    pattern,
    count: _count,
    startWith: _startWith,
    ...charsetOptions
  } = options;

  if (pattern) {
    return estimatePatternEntropy(pattern, charsetOptions);
  }

  const charset = buildCharset(charsetOptions);
  const charsetSize = charset.length;

  const effectiveLength = Math.max(0, length - prefix.length - suffix.length);

  if (effectiveLength === 0) {
    return {
      bits: 0,
      strength: 'very-weak',
      charsetSize,
      effectiveLength: 0,
      combinations: '1',
    };
  }

  const bitsPerChar = Math.log2(charsetSize);
  const bits = bitsPerChar * effectiveLength;

  return {
    bits: Math.round(bits * 100) / 100,
    strength: strengthLabel(bits),
    charsetSize,
    effectiveLength,
    combinations: approximateCombinations(charsetSize, effectiveLength),
  };
}

function estimatePatternEntropy(
  pattern: string,
  charsetOptions: Omit<RandomStringOptions, 'pattern' | 'length' | 'prefix' | 'suffix' | 'count' | 'startWith'>
): EntropyResult {
  const fullCharset = buildCharset(charsetOptions);
  const alphaChars = [...fullCharset].filter(c => /[a-zA-Z]/.test(c)).join('');
  const upperChars = [...fullCharset].filter(c => /[A-Z]/.test(c)).join('');
  const lowerChars = [...fullCharset].filter(c => /[a-z]/.test(c)).join('');
  const digitChars = '0123456789';
  const alphanumChars = [...fullCharset].filter(c => /[a-zA-Z0-9]/.test(c)).join('');

  let totalBits = 0;
  let effectiveLength = 0;
  let i = 0;

  while (i < pattern.length) {
    const ch = pattern[i] as string;

    if (ch === '\\' && i + 1 < pattern.length) {
      i += 2;
      continue;
    }

    let placeholderCharsetSize = 0;

    switch (ch) {
      case '#':
        placeholderCharsetSize = digitChars.length;
        effectiveLength++;
        break;
      case 'A':
        placeholderCharsetSize = Math.max(upperChars.length, 1);
        effectiveLength++;
        break;
      case 'a':
        placeholderCharsetSize = Math.max(lowerChars.length, 1);
        effectiveLength++;
        break;
      case '*':
        placeholderCharsetSize = fullCharset.length;
        effectiveLength++;
        break;
      case '?':
        placeholderCharsetSize = Math.max(alphanumChars.length, 1);
        effectiveLength++;
        break;
      default:
        // Literal character — contributes 0 entropy
        break;
    }

    if (placeholderCharsetSize > 0) {
      totalBits += Math.log2(placeholderCharsetSize);
    }

    i++;
  }

  const _ = alphaChars; // suppress unused warning

  return {
    bits: Math.round(totalBits * 100) / 100,
    strength: strengthLabel(totalBits),
    charsetSize: fullCharset.length,
    effectiveLength,
    combinations: approximateCombinations(fullCharset.length, effectiveLength),
  };
}

function strengthLabel(bits: number): EntropyResult['strength'] {
  if (bits < 28) return 'very-weak';
  if (bits < 50) return 'weak';
  if (bits < 72) return 'fair';
  if (bits < 100) return 'strong';
  return 'very-strong';
}

/**
 * Returns an approximate count of unique combinations as a string.
 * Uses scientific notation for very large numbers to avoid Infinity.
 */
function approximateCombinations(charsetSize: number, length: number): string {
  // log10(charsetSize^length) = length * log10(charsetSize)
  const log10 = length * Math.log10(charsetSize);
  if (log10 > 15) {
    const exp = Math.floor(log10);
    const mantissa = Math.pow(10, log10 - exp);
    return `${mantissa.toFixed(2)}e+${exp}`;
  }
  return Math.round(Math.pow(charsetSize, length)).toString();
}
